version: '3'
services:

  jupyter-notebook:
    build: .
    restart: unless-stopped
    environment:
      - MLFLOW_TRACKING_URI=file:///home/jovyan/mlruns
    ports:
      - "8889:8888"
    volumes:
      - ./data:/home/jovyan:z
    image: jupyter-notebook

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    command: mlflow server --host 0.0.0.0
    restart: unless-stopped
    ports:
      - "5001:5000"
    volumes:
      - ./data/mlruns:/home/jovyan/mlruns:z
    image: mlflow

